author:
  email: carsten@wulff.no
  name: Carsten Wulff
baseurl: /lelo_temp_sky130a
description: Example of a temperature sensor
domain: analogicus.com
exclude:
- Gemfile
- Gemfile.lock
- node_modules
kramdown:
  mathjax: true
markdown: kramdown
minima:
  skin: classic
plugins:
- jekyll-feed
- jemoji
- jekyll-seo-tag
- jekyll-remote-theme
- jekyll-paginate
remote_theme: wulffern/minima
show_excerpts: false
title: LELO_TEMP_SKY130A
url: https://analogicus.com
